apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: web-bff-config
spec:
  features:
    - name: SchedulerReminders
      enabled: false
  tracing:
    samplingRate: '1'
    otel:
      endpointAddress: 'localhost:4318'
      isSecure: false
      protocol: 'http'
  mtls:
    enabled: false
